### PR TITLE
Incredible description part 1

### PR DESCRIPTION
**Pull request by Samir-Rashid**
#1 This is a pull request to alleviate the glaring issues. In fact it is the only Issue at this moment and will clean your slate once again.

### CODE REVIEW

**Comment by grnnja** [comment]
> # Level Surfaces: a browser based 3D surface grapher
Although I would like it to, OpenSCAD does not work in the browser.

**Review by grnnja — CHANGES_REQUESTED** [review]
If we could change this to say it renders in the OpenSCAD program, that would improve the quality of this pull request.

**Comment by Samir-Rashid** [comment]
Yes I checked browser compatability, and although there is a browser renderer that defeats the point of writing this independently. :(

**Comment by Samir-Rashid** [comment]
> If we could change this to say it renders in the OpenSCAD program, that would improve the quality of this pull request.

on it, master

**Comment by grnnja** [comment]
Amazing work

**Pull request merged**
